Add example tests
concierge/HelloConcierge pull request #1
Opened 2017-05-10 09:17 UTC by Awarua-

2017-05-10 09:22 UTC, drkno requested changes

2017-05-10 09:22 UTC, mrkno commented on test/acceptance/hello.js
> +var assert = require('chai').assert,
ES6 for consistency with the rest of the codebase (you'll probably need 'use strict' at the top due to grunt + node4)

2017-05-10 09:28 UTC, Awarua- commented on test/acceptance/hello.js
> +var assert = require('chai').assert,
done

2017-05-10 09:29 UTC, mrkno commented on test/acceptance/hello.js
> +var assert = require('chai').assert,
... but we still have `function`s ...

2017-05-10 09:29 UTC, mrkno commented on test/unit/test.js
> +var assert = require('chai').assert;
and vars

2017-05-23 01:53 UTC, drkno approved these changes

2017-05-23 02:49 UTC, merged